server:
  port: 0

spring:
  application:
    name: AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /AUTH-SERVICE/v3/api-docs
  swagger-ui:
    path: /AUTH-SERVICE/swagger-ui.html