spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
          filters:
            - AuthenticationFilter


        - id: accounting-service
          uri: lb://ACCOUNTING-SERVICE
          predicates:
            - Path=/accountingBook/**
          filters:
            - AuthenticationFilter


        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**


  application:
    name: API-GATEWAY

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

